# Generated by Django 4.1.3 on 2022-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='images/'),
        ),
    ]
